import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/templates/Header";
import Footer from "@/components/templates/Footer";
import Products from "@/components/Products";
import { Container } from "./style";
import { useState } from "react";

export default function Home() {
  const [cart, setCart] = useState([]);
  return (
    <Container>
      <Head>
        <title>MKS Front-End Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header cart={cart} setCart={setCart} />
      <Products setCart={setCart} />
      <Footer />
    </Container>
  );
}
